
INSERT INTO FIGURAS(FIG_TIPO, FIG_NOMBRE, FIG_LADO) VALUES(1,"cua1",10)
INSERT INTO FIGURAS(FIG_TIPO, FIG_NOMBRE, FIG_LADO,FIG_APOTEMA,FIG_FIG_NUMLADOS) VALUES(5,"pr1",8,10,8)
INSERT INTO FIGURAS(FIG_TIPO, FIG_NOMBRE, FIG_RADIO) VALUES(2,"cir1",7)
INSERT INTO FIGURAS(FIG_TIPO, FIG_NOMBRE, FIG_BASE, FIG_ALTURA) VALUES(3,"r1",10,16)
INSERT INTO FIGURAS(FIG_TIPO, FIG_NOMBRE, FIG_BASE, FIG_ALTURA) VALUES(4,"T1",80,12)